services:
  postgres:
    image: postgres:16-alpine
    container_name: hubflow-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: hubflow
      POSTGRES_USER: hubflow_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Defina DB_PASSWORD no arquivo .env}

    ports:
      - "5433:5432"

    volumes:
      - hubflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hubflow_user -d hubflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hubflow-backend
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://postgres:5432/hubflow
      DATABASE_USERNAME: hubflow_user
      DATABASE_PASSWORD: ${DB_PASSWORD:?Defina DB_PASSWORD no arquivo .env}

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  hubflow_postgres_data:
