spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/hubflow}
    username: ${DATABASE_USERNAME:hubflow}
    password: ${DATABASE_PASSWORD:hubflow}
  flyway:
    locations: classpath:db/migration
